#!/bin/bash

# Copyright (C) 2007-2010 PlayOnLinux Team
# Copyright (C) 2007 Pâris Quentin

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. 

#Variables
die() ## PHP function copy
{
	echo "$@"
	exit
}
[ "$PLAYONLINUX" = "" ] || die "You are already in a PlayOnLinux environement" 
#Dans quel répértoire se trouve le script ?
PLAYONLINUX=`dirname "$0"`
cd "$PLAYONLINUX"
export PLAYONLINUX=`pwd`
source "$PLAYONLINUX/lib/sources"
if [ "$1" = "--version" ]
then
	echo "PlayOnLinux $VERSION"
	exit 0
fi

echo "PlayOnLinux v$VERSION"
echo ""
if [ ! "$(which $PYTHON)" ]
then
	missing "$PYTHON"
fi

start_pol "$@" 
echo ""
exit 0
