#!/bin/bash

# Copyright (C) 2007 Pâris Quentin

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. 

if [ "$PLAYONLINUX" = "" ]
then
exit 0
fi
source "$PLAYONLINUX/lib/sources"
cfg_check

LNG_KILL_WINSERVER=$(eval_gettext "Warning ! Before killing the wineserver, please assure that there are no wine applications running.

Are you sure you want to kill the wineserver ?")

LNG_KILLED_WINSERVER=$(eval_gettext "Wineserver killed")

POL_SetupWindow_Init "$PLAYONLINUX/etc/setups/wineserver/top.png" "$PLAYONLINUX/etc/setups/wineserver/left.jpg"
POL_SetupWindow_free_presentation "$(eval_gettext 'Kill wineserver process')" "$LNG_KILL_WINSERVER" 
killall wineserver
POL_SetupWindow_message "$LNG_KILLED_WINSERVER" "$(eval_gettext 'Kill wineserver process')"
POL_SetupWindow_Close

exit 
