#!/bin/bash

# Copyright (C) 2007-2010 PlayOnLinux Team
# Copyright (C) 2007 Pâris Quentin

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. 

if [ "$PLAYONLINUX" = "" ]
then
exit 0
fi
source "$PLAYONLINUX/lib/sources"
cfg_check

POL_SetupWindow_Init "$PLAYONLINUX/etc/setups/wineserver/top.png" "$PLAYONLINUX/etc/setups/wineserver/left.jpg"
POL_SetupWindow_free_presentation "$(eval_gettext 'Kill wineserver process')" "$(eval_gettext "Warning! This operation could make Wine applications unstable, whether they were launched by PlayOnLinux or not. Please make sure there are no Wine applications running before you continue.\n\nAre you sure you want to kill the wineserver?")" 
killall wineserver
POL_SetupWindow_message "$(eval_gettext "Wineserver killed")" "$(eval_gettext 'Kill wineserver process')"
POL_SetupWindow_Close

exit 
