#!/bin/bash

# Copyright (C) 2007-2010 PlayOnLinux Team
# Copyright (C) 2009 Pâris Quentin

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. 

if [ "$PLAYONLINUX" = "" ]
then
	exit 0
fi

source "$PLAYONLINUX/lib/sources" 

touch "$REPERTOIRE/configurations/last_string"
sleep 2
if [ ! "$OFFLINE" == "1" ]
then
	local_string=$(cat "$REPERTOIRE/configurations/last_string")
	if ( ! wget "$SITE/update_mark.txt" -O- -q 2> /dev/null > /dev/null)
	then
		exit
	fi
	remote_string=$(wget "$SITE/update_mark.txt" -O- -q 2> /dev/null)
	if [ ! "$local_string" = "$remote_string" ]
	then
		echo "$remote_string" > "$REPERTOIRE/configurations/last_string"
		echo "$(eval_gettext "The PlayOnLinux repository needs to be updated.")"
		maj_check
	fi
fi
