#!/bin/bash

# Copyright (C) 2009 Pâris Quentin

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. 

if [ "$PLAYONLINUX" = "" ]
then
	exit 0
fi

source "$PLAYONLINUX/lib/sources" 

if [ "$OFFLINE" == "1" ]
then
	message "$(eval_gettext "You are in offline mode")"
else
	maj_check
#	attendre "$(eval_gettext 'Updating')" "bash $PLAYONLINUX/bash/check_maj_" "$(eval_gettext 'Updating')" 0 0 0 "" 0 "$(eval_gettext 'The list of programs has been successfully updated')" "$(eval_gettext 'Finished')"
fi
