#!/bin/bash

# Copyright (C) 2007-2010 PlayOnLinux Team
# Copyright (C) 2007 Pâris Quentin
#  		     Cassarin-Grand Arthur

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA. 

if [ "$PLAYONLINUX" = "" ]
then
	exit 0
fi

source "$PLAYONLINUX/lib/sources" 

if [ "$1" == "--build" ]
then
			mkdir -p $HOME/.config/menus/applications-merged/
			mkdir -p $HOME/.config/menus/kde-applications-merged/
			mkdir -p $HOME/.local/share/applications
			mkdir -p $HOME/.local/share/desktop-directories
			mkdir -p $HOME/.local/share/icons
			generer_icone "playonlinux" "PlayOnLinux" "$HOME/.local/share/applications/" "$PLAYONLINUX/playonlinux" "PlayOnLinux"
			cp $PLAYONLINUX/etc/playonlinux-Programmes.menu $HOME/.config/menus/applications-merged/
			cp $PLAYONLINUX/etc/playonlinux-Programmes.menu $HOME/.config/menus/kde-applications-merged/
			cp $PLAYONLINUX/etc/PlayOnLinux.directory $HOME/.local/share/desktop-directories
			cp $PLAYONLINUX/etc/playonlinux.png $HOME/.local/share/icons
else
			rm $HOME/.config/menus/applications-merged/playonlinux-Programmes.menu 2> /dev/null
			rm $HOME/.config/menus/kde-applications-merged/playonlinux-Programmes.menu 2> /dev/null
fi


